// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile, role and assigned centre.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error }, { data: roles }] = await Promise.all([
      supabase.from("profiles").select("full_name, employee_id, phone, is_active, centre_id, centres(name)").eq("user_id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = {
      email: ctx.getUserEmail() ?? null,
      profile: profile ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-visits.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";
var dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD");
var list_visits_default = defineTool2({
  name: "list_visits",
  title: "List field visits",
  description: "List field visits (doctor, hospital, lab, pharmacy, ambulance, KOL, other) visible to the signed-in user, optionally filtered by date range and visitor type.",
  inputSchema: {
    from: dateSchema.optional().describe("Start visit date (inclusive), YYYY-MM-DD."),
    to: dateSchema.optional().describe("End visit date (inclusive), YYYY-MM-DD."),
    visitor_type: z.string().optional().describe("Filter by visitor type, e.g. doctor, hospital, lab."),
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, visitor_type, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("visits").select(
      "id, visit_date, visitor_name, visitor_type, designation, doctor_name, place, purpose, notes, checkin_time, checkout_time, centres(name)"
    ).order("visit_date", { ascending: false }).limit(limit ?? 50);
    if (from) query = query.gte("visit_date", from);
    if (to) query = query.lte("visit_date", to);
    if (visitor_type) query = query.eq("visitor_type", visitor_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, visits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-referrals.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var dateSchema2 = z2.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD");
var list_referrals_default = defineTool3({
  name: "list_referrals",
  title: "List referrals",
  description: "List patient referrals visible to the signed-in user, optionally filtered by date range and procedure type (CAG/PTCA).",
  inputSchema: {
    from: dateSchema2.optional().describe("Start referral date (inclusive), YYYY-MM-DD."),
    to: dateSchema2.optional().describe("End referral date (inclusive), YYYY-MM-DD."),
    procedure_type: z2.string().optional().describe("Filter by procedure type, e.g. cag or ptca."),
    limit: z2.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, procedure_type, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("referrals").select(
      "id, referral_date, patient_name, patient_count, procedure_type, service_type, hospital_name, referral_centre, referral_received, estimated_value, notes, centres(name)"
    ).order("referral_date", { ascending: false }).limit(limit ?? 50);
    if (from) query = query.gte("referral_date", from);
    if (to) query = query.lte("referral_date", to);
    if (procedure_type) query = query.eq("procedure_type", procedure_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const summary = {
      count: rows.length,
      patients: rows.reduce((n, r) => n + (r.patient_count ?? 0), 0),
      estimated_value: rows.reduce(
        (n, r) => n + Number(r.estimated_value ?? 0),
        0
      )
    };
    return {
      content: [{ type: "text", text: JSON.stringify({ summary, referrals: rows }, null, 2) }],
      structuredContent: { ...summary, referrals: rows }
    };
  }
});

// src/lib/mcp/tools/get-activity-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var dateSchema3 = z3.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD");
var get_activity_summary_default = defineTool4({
  name: "get_activity_summary",
  title: "Get daily activity summary",
  description: "Summarise field activity for a date range: working days, total KM travelled, visit counts by type, and referral totals.",
  inputSchema: {
    from: dateSchema3.describe("Start date (inclusive), YYYY-MM-DD."),
    to: dateSchema3.describe("End date (inclusive), YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const [checkins, visits, referrals] = await Promise.all([
      supabase.from("daily_checkins").select("id, checkin_date, status, total_km, gps_km").gte("checkin_date", from).lte("checkin_date", to),
      supabase.from("visits").select("visitor_type, visit_date").gte("visit_date", from).lte("visit_date", to),
      supabase.from("referrals").select("patient_count, procedure_type, estimated_value, referral_date").gte("referral_date", from).lte("referral_date", to)
    ]);
    const error = checkins.error || visits.error || referrals.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const visitsByType = {};
    for (const v of visits.data ?? []) {
      const key = String(v.visitor_type);
      visitsByType[key] = (visitsByType[key] ?? 0) + 1;
    }
    const summary = {
      range: { from, to },
      working_days: (checkins.data ?? []).length,
      total_km: (checkins.data ?? []).reduce(
        (n, c) => n + Number(c.total_km ?? c.gps_km ?? 0),
        0
      ),
      total_visits: (visits.data ?? []).length,
      visits_by_type: visitsByType,
      referrals: (referrals.data ?? []).length,
      referred_patients: (referrals.data ?? []).reduce(
        (n, r) => n + (r.patient_count ?? 0),
        0
      ),
      cag: (referrals.data ?? []).filter((r) => r.procedure_type === "cag").length,
      ptca: (referrals.data ?? []).filter((r) => r.procedure_type === "ptca").length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-monthly-activities.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var list_monthly_activities_default = defineTool5({
  name: "list_monthly_activities",
  title: "List monthly activities",
  description: "List planned monthly activities (CMEs, camps, meetings) visible to the signed-in user.",
  inputSchema: {
    status: z4.string().optional().describe("Filter by status, e.g. planned, completed, cancelled."),
    limit: z4.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("monthly_activities").select(
      "id, activity_name, activity_date, expected_completion_date, completion_date, location, status, notes, completion_notes, centres(name)"
    ).order("activity_date", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, activities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leave-requests.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^4.4.3";
var list_leave_requests_default = defineTool6({
  name: "list_leave_requests",
  title: "List leave requests",
  description: "List leave requests visible to the signed-in user, optionally filtered by status.",
  inputSchema: {
    status: z5.string().optional().describe("Filter by status, e.g. pending, approved, rejected."),
    limit: z5.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("leave_requests").select("*").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, leave_requests: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xwoskogftcdzkxaqowih";
var mcp_default = defineMcp({
  name: "centre-connect-pro",
  title: "Centre Connect Pro",
  version: "0.1.0",
  instructions: "Read-only tools for Centre Connect Pro, a referral marketing system for cardiac centre field staff. Use `whoami` for the caller's profile and role, `get_activity_summary` for KM/visit/referral totals over a date range, and the list tools for visits, referrals, monthly activities and leave requests. All data is scoped to what the signed-in user is allowed to see.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    get_activity_summary_default,
    list_visits_default,
    list_referrals_default,
    list_monthly_activities_default,
    list_leave_requests_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
